/* This file was automatically generated by rbautoimp.awk
		MANUAL EDITING NOT RECOMMENDED! */

#include "rb_global.h"

int rb_register_std( void )
{
	PROC( "rb_register_std" );

	MSG( "Registering function 'trimvar'" );
	rb_add_native_function( "trimvar", trimvar, TRUE, "v", RB_FUNC_AT_RUNTIME );
	MSG( "Registering function 'getlen'" );
	rb_add_native_function( "getlen", getlen, TRUE, "v", RB_FUNC_AT_RUNTIME );
	MSG( "Registering function 'getcharat'" );
	rb_add_native_function( "getcharat", getcharat, TRUE, "vv", RB_FUNC_AT_RUNTIME );
	MSG( "Registering function 'gettok'" );
	rb_add_native_function( "gettok", gettok, TRUE, "vvv", RB_FUNC_AT_RUNTIME );
	MSG( "Registering function 'getpos'" );
	rb_add_native_function( "getpos", getpos, TRUE, "vvv", RB_FUNC_AT_RUNTIME );
	MSG( "Registering function 'replacevar'" );
	rb_add_native_function( "replacevar", replacevar, TRUE, "vvv", RB_FUNC_AT_RUNTIME );

	RETURN( 0 );
}
