#ifndef LANGUAGE_H
#define LANGUAGE_H

#define LNG_TOOLTIP_NEWFILE 0
#define LNG_TOOLTIP_OPENFILE 1
#define LNG_TOOLTIP_SAVEFILE 2
#define LNG_TOOLTIP_FIND 3
#define LNG_TOOLTIP_COPY 4
#define LNG_TOOLTIP_CUT 5
#define LNG_TOOLTIP_PASTE 6
#define LNG_TOOLTIP_RUN 7
#define LNG_TOOLTIP_HELP 8
#define LNG_TOOLTIP_DELETE 9
#define LNG_TOOLTIP_UNDO 10
#define LNG_TOOLTIP_REDO 11

#define LNG_DLG_FILEOPEN 100
#define LNG_DLG_FILESAVE 101

#define LNG_DEFAULTFILE 102

#define LNG_DLG_FIND_TITLE 103
#define LNG_DLG_FIND_OK 104
#define LNG_DLG_FIND_CANCEL 105

#define LNG_DLG_SETCOMMAND_TITLE 106
#define LNG_DLG_SETCOMMAND_OK 107
#define LNG_DLG_SETCOMMAND_CANCEL 108

#define LNG_DLG_GOTOLINE_TITLE 109
#define LNG_DLG_GOTOLINE_OK 110
#define LNG_DLG_GOTOLINE_CANCEL 111
#define LNG_DLG_GOTOLINE_PROMPT 112

#define LNG_MSG_SAVEANYCHANGES 200
#define LNG_MSG_NORESULTSFOUND 201
#define LNG_MSG_FILEEXISTS 202
#define LNG_MSG_COMPILEERROR 203
#define LNG_MSG_COMPILESUCCEED 204

#define LNG_DLG_COMPILE_OPENICON 205
#define LNG_DLG_COMPILE_TITLE 206
#define LNG_DLG_COMPILE_COMPILEBUTTON 207
#define LNG_DLG_COMPILE_CANCELBUTTON 208
#define LNG_DLG_COMPILE_AUTOLINK 209
#define LNG_DLG_COMPILE_LINKICON 210
#define LNG_DLG_COMPILE_RUNAFTERHALT 211

#define LNG_DLG_DEBUG_TITLE 212
#define LNG_DLG_DEBUG_OKBUTTON 213
#define LNG_DLG_DEBUG_CANCELBUTTON 214
#define LNG_DLG_DEBUG_DEBUGSCRIPT 215
#define LNG_DLG_DEBUG_STEP 216
#define LNG_DLG_DEBUG_TRACE 217
#define LNG_DLG_DEBUG_NONE 218
#define LNG_DLG_DEBUG_AUTO 219
#define LNG_DLG_DEBUG_MANUAL 220
#define LNG_DLG_DEBUG_DEBUGMODE 221
#define LNG_DLG_DEBUG_VARMON 222

#define LNG_DLG_ABOUT_REFERLICENSE 223

#define LNG_DYNAMICMENU_TOOLS 500
#define LNG_DYNAMICMENU_HISTORY 501
#define LNG_DYNAMICMENU_TOOLS_CONFIGURE 502

#define LNG_CONTEXTMENU_COPY 250
#define LNG_CONTEXTMENU_CUT 251
#define LNG_CONTEXTMENU_PASTE 252
#define LNG_CONTEXTMENU_SELECT_ALL 253
#define LNG_CONTEXTMENU_DELETE 254

#endif

